octopus.lo: /home/bud/newoctopusd/octopusd/octopusd_phpext/octopus.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/bud/newoctopusd/octopusd/octopusd_phpext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/bud/newoctopusd/octopusd/octopusd_phpext/octopus.c -o octopus.lo 
oct_cli.lo: /home/bud/newoctopusd/octopusd/octopusd_phpext/oct_cli.c
	$(LIBTOOL) --mode=compile $(CC)  -I. -I/home/bud/newoctopusd/octopusd/octopusd_phpext $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/bud/newoctopusd/octopusd/octopusd_phpext/oct_cli.c -o oct_cli.lo 
$(phplibdir)/octopus.la: ./octopus.la
	$(LIBTOOL) --mode=install cp ./octopus.la $(phplibdir)

./octopus.la: $(shared_objects_octopus) $(OCTOPUS_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_octopus) $(OCTOPUS_SHARED_LIBADD)

